### ISSUE TITLE
Linea de capacitación 1

### ISSUE THREAD

**Issue by AleeGabb** [fauzcategui/moodle-sence#11]
Hola!
Junto con agradecer el gran trabajo que has desarrollado tengo una duda, actualmente estoy implementando tu plugin a una OTEC que trabaja en la línea de capacitación 1 pero no he logrado hacer que funcione correctamente, me lanza un mensaje que los alumnos no están autorizados para el curso, me parece mucho que tiene que ver con la configuración de los grupos o quizás no esta habilitado el plugin para esta línea... agradecería si me pudieras aclarar esto. Muchas gracias de antemano.

**Comment by fauzcategui** [comment]
v3.2 resuelve este problema
