### ISSUE TITLE
Consulta Líneas de capacitación

### ISSUE THREAD

**Issue by effexts** [fauzcategui/moodle-sence#2]
Hola.
Buscando información sobre la integración de sence con moodle, di con tu repositorio y me parece excelente que puedas compartir tu visión del proceso. 

Y tengo una consulta con respecto a esta línea.

https://github.com/fauzcategui/moodle-sence/blob/4ba541089bcbbafb9b9c7b2af97a6e6a0a4a6874/edit_form.php#L7

Es necesaria para la integración con la plataforma de registro de asistencia de sence?
He leído los manuales y varios sitios, pero en ningún lado me he encontrado con este dato. 
Es sólo para ordenar y categorizar o para algo que lleve mas funcionalidad?

Gracias. 

Por cierto, con gusto te puedo ayudar a finalizar este plugin que es bastante útil, y que me está ayudando a realizar la integración en un sistema de un familiar.

Saludos.

**Comment by fauzcategui** [comment]
Hola, 

Este es un parametro que debe enviarse en el formulario de forma obligatoria, lamentablemente la documentación de SENCE no da mucha información. El valor por defecto es 3 y se que existe el 1 pero aún estoy investigando cuales serían los casos que aplican (Por eso lo deje comentado mientras), pero enviando el valor por defecto debería funcionarte.

Se aceptan pull request para mejorar este plugin, por ahora tiene toda la funcionalidad que yo necesitaba pero puedes enviar las sugerencias que consideres para agregarlas como una lista de tareas!

Saludos!

**Comment by effexts** [comment]
Si, tienes razón... re-leí la documentación y si lo pide. 
Aún no he hecho ninguna prueba, pero apenas pueda lo revisaré y si encuentro que se pueda mejorar, no dudaré en avisar.

Muchas gracias!
