### ISSUE TITLE
Consulta redireccionamiento

### ISSUE THREAD

**Issue by lalrop** [fauzcategui/moodle-sence#3]
Hola, 
Buscando entre soluciones para este tema, encontre tu repositorio y me parece excelente lo que estas haciendo.

Lo intente probar en mi plataforma Moodle, pero para las cuentas de alumnos solamente muestra el mensaje de de Bienvenido mas no da indicios de redireccionamiento al portal de SENCE para hacer la autenticacion.

Existe alguna notacion en especifico para señalar a los alumnos en la lista de alumnos del bloque? Intente mediante el username, firstname, lastname, rut...

Me quedo atento y nuevamente se agradece tu iniciativa

**Comment by fauzcategui** [comment]
Hola, he actualizado el README con las instrucciones para su implementación y unas aclaratorias al principio
https://github.com/fauzcategui/moodle-sence/blob/stable/README.md
